name: project_odata
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  http: ^1.1.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  barcode_scan2: ^4.2.0
  supabase_flutter: ^2.10.1
  sqflite_common_ffi: ^2.3.6
  intl: ^0.20.2
  sqflite: ^2.4.2
  json_annotation: ^4.9.0
  objectbox: ^4.3.1
  objectbox_flutter_libs: ^4.3.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  objectbox_generator: ^4.3.1

flutter:
  uses-material-design: true
